### PR TITLE
CB-14-zipcode

### PR DESCRIPTION
**Pull request by Aarushi-Pandey**
* **Please check if the PR fulfills these requirements**
- [x] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
It creates a component to accept a zipcode and distance that the user wants to travel.

* **What is the current behavior?What does the code do before you made the new changes?** 
No component to accept zipcode or distance travelled from the user.

* **What is the new behavior?**
There is now a component to accept 2 inputs- a zipcode and distance that the user wants to travel. It currently displays the user inputs as a way to check if the code is working (will remove them once the zipcode API is working).

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
No, although the LnadingPage component needs to be changed to include this component.

* **Other information**:

### CODE REVIEW

**Comment by JerryTeng01** [comment]
hi aarushi, it looks like you never filled out the pr form

**Comment by Aarushi-Pandey** [comment]
Thanks for pointing that out Jerry! I've updated the pr form, let me know if you have any comments or concerns!

**Comment by Codubee** [comment]
Hey Aarushi. Did you make this branch off of main branch? I see that Jerrys routing code is not in your branch here.

**Comment by Aarushi-Pandey** [comment]
Yes I did. It's been awhile since I made this branch, so some recent pull requests won't be visible here. Thinking about whether I should add those changes to this branch.

**Comment by Aarushi-Pandey** [comment]
I've updated my code with the code in the main branch. Made a new component for the user input in the frontend folder too. There is a problem with the styling in the LandingPage component, hopefully I can fix this later.

**Review by georg469256 — APPROVED** [review]
Component looks great Aarushi! It looks like the inline css is only used where necessary and you made all the changes that were requested in the meeting. Good work!

**Review by Codubee — APPROVED** [review]
LGTM!

**Pull request merged**
