### PR TITLE
Cb 5 features

### PR DESCRIPTION
**Pull request by gustavooviedo**
* **Please check if the PR fulfills these requirements**
- [x] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
Added features component and removed default comments in LandingPage

* **What is the current behavior?What does the code do before you made the new changes?** 
New component

* **What is the new behavior?**
Displays the features of the website to the user

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
None should be needed

* **Other information**:

### CODE REVIEW

**Review by JerryTeng01 — APPROVED** [review]
Hello Gustavo! This looks good to me. The only improvement I would make is adding some styling to center the text and make it stand out a bit more. We'll probably be adding to our features component throughout the course of the project, so feel free to implement some css or perhaps a reactstrap component to spice it up a bit. Other than that, good work!

**Comment by Aarushi-Pandey** [comment]
Hi Gustavo, I think you've done a good job of including all of our planned features (so far). I agree with what Jerry said, and I'd like it if you added a heading to the page as well as centered the text. I think some styling can definitely make the page more professional-looking and aesthetically pleasing. Using reactstrap might help with that. Everything else looks great! Keep up the good work!

**Comment by gustavooviedo** [comment]
Thank you, Jerry and Aarushi for the feedback! I have added some styling to the component and would love to hear any more feedback if any. I considered matching my component to Aarushi's theme but realized that there will be a time in which we decide on an overall style for the website. I implemented a different style instead in case it inspires some ideas. Again, thanks for the review!

**Review by Codubee — APPROVED** [review]
LGTM

**Pull request merged**
