### PR TITLE
Cb 13 show things to do

### PR DESCRIPTION
**Pull request by sulemanbutta**
* **Please check if the PR fulfills these requirements**
- [X] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
Creates page to show things to do from the api

* **What is the current behavior?What does the code do before you made the new changes?** 
No current behavior to show things to do

* **What is the new behavior?**
Gets data from API and backend and presents it on the explore page

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
No breaking change

* **Other information**:

### CODE REVIEW

**Comment by Aarushi-Pandey** [comment]
I'm unable to see the ThingsToDo component in "/explore". This might be due to nothing being mapped to the page (There is nothing in the container so I just see the NavBar). Because of this, I'm unable to judge approve this PR. Also, there are some files changed that are unrelated to this branch. Maybe remove those files from this PR. Sorry to not be of much help, but I'm sure your work is great! Good luck!

**Comment by sulemanbutta** [comment]
> I'm unable to see the ThingsToDo component in "/explore". This might be due to nothing being mapped to the page (There is nothing in the container so I just see the NavBar). Because of this, I'm unable to judge approve this PR. Also, there are some files changed that are unrelated to this branch. Maybe remove those files from this PR. Sorry to not be of much help, but I'm sure your work is great! Good luck!

I am unsure why this is, since it works on my end. I will look into it and see what the problem is. Thanks

**Review by JerryTeng01 — APPROVED** [review]
Hey Suleman, this looks pretty good! I see that we had the same idea to use Bootstrap icons. One minor improvement you could make is adding a condition so the phone icon only shows up when the phone field is not blank. Also it might be a good idea to remove package-lock.json to make things more convenient. Good job!

**Comment by sulemanbutta** [comment]
> Hey Suleman, this looks pretty good! I see that we had the same idea to use Bootstrap icons. One minor improvement you could make is adding a condition so the phone icon only shows up when the phone field is not blank. Also it might be a good idea to remove package-lock.json to make things more convenient. Good job!

Thanks! I saw yours and tried to add some of what you did to maintain some consistency between our pages. I think the issue with the package-lock.json is that I have newer versions packages installed on my machine. I am not sure how to remove the files from the PR but I'll try again to sort it out.

**Comment by georg469256** [comment]
I am unable to see this component or Jerry's. Is this the case in anyone else's machine?

**Review by georg469256 — APPROVED** [review]

**Comment by georg469256** [comment]
Error on my end. Component looks good Suleman!

**Pull request merged**
